### ISSUE TITLE
Using conftest-action with multiple files?

### ISSUE THREAD

**Issue by dmitri-lerko** [instrumenta/conftest-action#1]
Great to see conftest as GitHub action.

I have successfully run it for a single deployment file following provided example. When I've tried to run conftest for a few files, it didn't work out.

**Works**
```
      with:
        files: app/deployment.yaml
```
**Does not work**
```
      with:
        files: app/deployment.yaml app2/deployment.yaml
```
***Does not work**
```
      with:
        files: app/deployment.yaml,app2/deployment.yaml
```

Fixing this would be a first step towards usability of the given GitHub action. However, I also feel that in larger, real-world repos it is not sustainable to provide a list of all yaml files in advance. Instead, a way to gather inputs programatically using pattern matching would be preferred.

Lastly, I am using kustomize, which makes it even harder to apply conftest.

Looking forward to finding ways for getting more out of conftest Actions.

**Comment by garethr** [comment]
Have you tried this with wildcards? ie. `files: */deployment.yaml`. Or try quoting `files: "app/deployment.yaml app2/deployment.yaml"`

If neither work if you could post the error messages you see as well.

We're currently talking about a hooks mechanism which will make integration with tools like kustomize much easier.

**Comment by jutley** [comment]
I'm running into this issue as well. The conftest command does not accept wildcards, and multiple file within quotes to not get separated. I've used an extra Action step to generate a list of all the files I want, but since they are all added as a single docker arg, I believe docker is then quoting the files.

In my case, the error is essentially:

```
Error: get configurations: get config: open file: open file1 file2 file file4 ... filen: file name too long
```

**Comment by jutley** [comment]
If conftest supported a directory as input (and recursively used every child file as input), then it would be easy to provide that directory name as the parameter.
